version: 0.0
os: linux
files:
 - source: Dockerfile
   destination: /home/ec2-user/
 - source: index.html
   destination: /home/ec2-user/
hooks:
  ApplicationStart:
    - location: Scripts/deploy.sh
      timeout: 3600
