version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_REPO
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_NAME .
      - docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REPO/$IMAGE_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECR_REPO/$IMAGE_NAME:$IMAGE_TAG
      - aws ssm put-parameter --name "/CodeBuild/IMAGE_ID" --value $ECR_REPO/$IMAGE_NAME:$IMAGE_TAG --overwrite
      - printf '[{"ImageUri":"%s"}]' $ECR_REPO/$IMAGE_NAME:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
