version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:871739047920:task-definition/blue-green:3" 
        LoadBalancerInfo:
          ContainerName: "blue-green"
          ContainerPort: 80
